adding doc yaml, adding new test and splitting by endpoint, adding PO…
pbbg/api.pbbg.com pull request #9
Opened 2020-10-10 14:38 UTC by foohonpie

…ST games endpoint

2020-10-10 16:08 UTC, mink commented on app/Http/Requests/PostGamesRequest.php
> +        return auth('api')->guest();
Are unauthenticated users allowed to submit a game?

2020-10-10 16:14 UTC, bpkennedy requested changes

2020-10-10 16:14 UTC, bpkennedy commented on tests/Feature/Games/PostGamesTest.php
> +        $response->assertStatus(422);
Interesting choice of 422 for this.  I'm reading more about the spec differences between 400 and 422 and I suppose it comes down to "malformed syntax" versus ok-formed and simply unprocessable.

For this, I would question since we are using PHP validation and types to say that url should be a `url` then aren't we in malformed territory and this a 400 is appropriate?

2020-10-10 16:14 UTC, bpkennedy commented on tests/Feature/Games/PostGamesTest.php
> +<?php
Do we also want to make a test that checks/prevents duplicates (since that's part of the validation of a create game POST request)?

2020-10-10 16:39 UTC, mink commented on tests/Feature/Games/PostGamesTest.php
> +        $response->assertStatus(422);
Laravel automatically returns HTTP 422 for input validation errors that come from AJAX requests.

This request could be considered well-formed with semantically incorrect contents, though either 400 or 422 could be valid for this request.

2020-10-10 16:46 UTC, foohonpie commented on app/Http/Requests/PostGamesRequest.php
> +        return auth('api')->guest();
Woops, good catch!

Users and guests should both be allowed to submit.

2020-10-10 19:02 UTC, foohonpie commented on tests/Feature/Users/GetAuthenticatedUserTest.php
> +    public function testAnUnauthetnicatedUserCannotAccessTheUserPage()
Eyes of steel!  That's maybe not the right phrase.  🤔

2020-10-11 00:32 UTC, foohonpie commented on tests/Feature/Games/GetGamesTest.php
> +<?php
I only see it once.  There's GetGames plural and GetGame singular though, was that what you were seeing?

2020-10-11 00:33 UTC, foohonpie commented on tests/Feature/Games/PostGamesTest.php
> +<?php
Yeah, there are some additions to User tests I'd like to do too, plus some DRY optimizations.  I'll put details up in a ticket.

2020-10-11 00:33 UTC, foohonpie commented on tests/Feature/Games/PostGamesTest.php
> +<?php
Yeah, there are some additions to User tests I'd like to do too, plus some DRY optimizations. I'll put details up in a follow-up ticket for test improvements.

2020-10-11 00:45 UTC, bpkennedy approved these changes

2020-10-11 00:51 UTC, merged